openapi: "3.0.0"
info:
  description: "Parallel Requests Service"
  version: "1.0.0"
  title: "ParallelRequestsService"
  contact:
    email: "angel.fernandez.sobrino@upc.edu"
servers:
  - url: https://parallel.ecobulk.upc.edu/
    description: ESXCluster
security:
  - ApiKeyAuth: []
paths:
  /parallel/get:
    post:
      summary: "Makes get requests"
      description: ""
      operationId: "makegetrequests"
      responses:
        "200":
          description: "OK"
  /parallel/post:
    post:
      summary: "Makes post requests"
      description: ""
      operationId: "makepostrequests"
      responses:
        "200":
          description: "OK"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: APIkey
