name: Deployment action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-and-deployment:
    runs-on: ubuntu-latest
    name: Release and deploy in server
    steps:
      - uses: actions/checkout@main
      - uses: mcia-services/release-copy-deploy-action@latest
        with:
          host: docker
          username: mcia
          key: ${{ secrets.DOCKER_PRIVATE_KEY }}
          proxy-host: 'mciawebserver.upc.edu'
          proxy-username: 'mcia'
          proxy-key: ${{ secrets.GATEWAY_PRIVATE_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: /home/mcia/services
          sources: bin src package.json package-lock.json Dockerfile .dockerignore docker-compose.yaml
          tag: latest
          script: |
            docker-compose up --build -d